spring.application.name=startUp


spring.datasource.url=jdbc:postgresql://localhost:5432/startUp
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

secret.jwt=8c272fe7-96a7-4324-a422-649c45c42627

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2s


api.path.dir=C:\\files