spring.application.name=startUp

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

secret.jwt=${JWT_SECRET}

spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.timeout=2s

spring.n8n.user=${N8N_USER}
spring.n8n.password=${N8N_PASSWORD}
spring.n8n.host=${N8N_HOST}
spring.n8n.port=${N8N_PORT}

api.path.dir=${PATH_DIR}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB